version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: blog_pass
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: